### ISSUE TITLE
TypeError: load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by arkinrc** [leggedrobotics/DeLORA#13]
Hi. I am trying to learn and train the provided rosbag dataset however after complete environment successfully installation, i am unable to run pre-process.py. Have got the following error plz guide me. thanks

```
preprocess_data.py
Checking whether path to ./datasets/darpa exists.
----------------------------------
Run for the datasets: ['darpa']
which are located at
./datasets/darpa
and will be stored at
./datasets/darpa/preprocessed/sequences
----------
Continue? (y/n): y
----------------------------------
Configuration for this run: 
{'horizontal_field_of_view': [-3.139847324337799, 3.139847324337799], 'min_num_points_in_neighborhood_to_determine_point_class': 10, 'epsilon_plane': 0.01, 'epsilon_line': 0.01, 'epsilon_range': 0.5, 'kitti': {'training_identifiers': [0, 1, 2, 3, 4, 5, 6, 7, 8], 'testing_identifiers': [9, 10], 'vertical_field_of_view': [-24.5, 2.0], 'vertical_cells': 64, 'horizontal_cells': 720, 'preprocessed_path': './datasets/kitti/preprocessed/sequences', 'pose_data_path': './datasets/kitti/data_odometry_poses/dataset/poses', 'dataset_type': 'kitti', 'horizontal_cells_preprocessing': 2250, 'neighborhood_side_length': [7, 11], 'data_path': './datasets/kitti/data_odometry_velodyne/dataset/sequences', 'rosbag_path': './datasets/kitti/rosbags/'}, 'darpa': {'training_identifiers': [0], 'testing_identifiers': [0], 'vertical_field_of_view': [-0.39269908169872414, 0.39269908169872414], 'vertical_cells': 64, 'horizontal_cells': 512, 'preprocessed_path': './datasets/darpa/preprocessed/sequences', 'pose_data_path': None, 'dataset_type': 'rosbag', 'topic': '/sherman/lidar_points', 'horizontal_cells_preprocessing': 512, 'neighborhood_side_length': [7, 11], 'data_path': './datasets/darpa', 'data_identifiers': [0, 0]}, 'custom': None, 'datasets': ['darpa'], 'mode': 'training', 'experiment': 'trainings_experiments_1', 'device': device(type='cuda'), 'store_dataset_in_RAM': False, 'num_dataloader_workers': 0, 'unsupervised_at_start': False, 'inference_only': True, 'log_normals': True, 'visualize_images': True, 'visualize_single_img_preprocessing': False, 'use_jit': False}
----------------------------------
Loading rosbag ./datasets/darpa/00.bag...
...done.
Traceback (most recent call last):
  File "/home/arkin/anaconda3/envs/DeLORA-py3.9/bin/preprocess_data.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/arkin/DeLORA/bin/preprocess_data.py", line 80, in <module>
    preprocesser.preprocess_data()
  File "/home/arkin/DeLORA/src/preprocessing/preprocesser.py", line 96, in preprocess_data
    rosbag_preprocessor = data.rosbag_scans.RosbagDatasetPreprocessor(config=self.config,
  File "/home/arkin/DeLORA/src/data/rosbag_scans.py", line 36, in __init__
    self.rosbag_extractor = ros_utils.rosbag_pcl_extractor.RosbagToPCLExtractor(
  File "/home/arkin/DeLORA/src/ros_utils/rosbag_pcl_extractor.py", line 25, in __init__
    info_dict = yaml.load(self.bag._get_yaml_info())
TypeError: load() missing 1 required positional argument: 'Loader'
```

I am using ubuntu 20.04 with ros-noetic ...

Looking forward to your feedback. 

Regards
Arkin

**Comment by arkinrc** [comment]
@nubertj  could you plz check this issue? thanks

**Comment by arkinrc** [comment]
problem has beeen solved.
